### ISSUE TITLE
Create a jobs section

### ISSUE THREAD

**Issue by jschiarizzi** [bkrem/awesome-solidity#55]
Idea: There should be a jobs section for listing solidity developer jobs and places to earn using solidity. Would be nice to have more places for listing jobs specific for developers, since most crypto job boards are cluttered with community manager and other non dev roles.

Possible entries include:
- gitcoin.co for earning
- EthHole.com for developer focused ethereum job board

**Comment by bkrem** [comment]
Yes, also a great suggestion 👍 

Feel free to add a PR with a new section + any links you think would be useful; it's your idea so I don't want to add it without providing some kind of credit.
