### ISSUE TITLE
BEN Jobs link gives 404 error

### ISSUE THREAD

**Issue by BrunoDavies** [bkrem/awesome-solidity#66]
The link under the sub-section "Jobs" for BEN Jobs gives a 404. https://blockchainedu.org/jobs. 

Could not find a new link on the website, not sure if they still do this.

**Comment by bkrem** [comment]
Thanks for making me aware of this 🙏 The build job wasn't catching this because the URL still returns `200` while showing a `404`.

Removed since the Jobs page seems to have been deleted from the domain completely.
